version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/app/dist
    ports:
      - 80:80