name: Merge on Dev
on:
  push:
    branches:
      - dev
jobs:
  transition-issue:
    name: Transition Issue
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find Issue Key
        id: find
        uses: atlassian/gajira-find-issue-key@master
        continue-on-error: true
        with:
          # https://github.com/atlassian/gajira-find-issue-key#usage
          # Each merge commit contains pull request name, which in turn may contains JIRA ticket name as a suffix in brackets
          # Eg this merge commit's name is pull request's 268 name, which contains JIRA ticket name PIX-2579
          # "[TECH] Ajouter le script d'automatisation JIRA post-merge (PIX-2579)."
          # https://github.com/1024pix/pix-site/commit/ac7e97b795b34cfef7c117cf5b95e48fdb309df5
          # https://github.com/1024pix/pix-site/pull/268
          from: commits

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        if: ${{ steps.find.outputs.issue }}
        with:
          issue: ${{ steps.find.outputs.issue }}
          transition: "Move to 'Deployed in Integration'"
